name: Test against corpus
on:
  push:
    branches: ["**"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.18.0
          run_install: true
      - name: Test against corpus
        run: pnpm run test
      - name: Ensure no generate changes
        run: git --no-pager diff --exit-code
